import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Session_Provider from "@/components/SessionProvider";
import { Toaster } from "@/components/ui/sonner"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session_Provider>
          <Toaster position="top-right" richColors/>
          {children}
        </Session_Provider>
      </body>
    </html>
  );
}
